version: "3.9"

services:
  mysql-db:
    image: mysql:5.7
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: employee_db
      MYSQL_USER: empuser
      MYSQL_PASSWORD: emppass
    volumes:
      - ./database:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    networks:
      - emp_net

  backend:
    build: ./backend
    container_name: flask-backend
    restart: always
    depends_on:
      - mysql-db
    ports:
      - "5000:5000"
    networks:
      - emp_net

  frontend:
    build: ./frontend
    container_name: nginx-frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "8080:80"
    networks:
      - emp_net

networks:
  emp_net:
