version: "3.9"

services:
  # Database Service
  db:
    image: mysql:5.7
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: employee_db
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - emp_net

  # Backend Flask Service
  backend:
    build: ./backend
    container_name: flask-backend
    restart: always
    depends_on:
      - db
    environment:
      - JWT_SECRET_KEY=super-secret-key
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=password
      - DB_NAME=employee_db
    ports:
      - "5000:5000"
    networks:
      - emp_net

  # Frontend Nginx Service
  frontend:
    build: ./frontend
    container_name: nginx-frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "8080:80"
    networks:
      - emp_net

networks:
  emp_net:

volumes:
  db_data:
